export const QUESTION_ONE_REQUEST = "QUESTION_ONE_REQUEST";
export const QUESTION_ONE_SUCCESS = "QUESTION_ONE_SUCCESS";
export const QUESTION_ONE_FAIL = "QUESTION_ONE_FAIL";

export const QUESTION_ONE_POINT_TWO_REQUEST = "QUESTION_ONE_POINT_TWO_REQUEST";
export const QUESTION_ONE_POINT_TWO_SUCCESS = "QUESTION_ONE_POINT_TWO_SUCCESS";
export const QUESTION_ONE_POINT_TWO_FAIL = "QUESTION_ONE_POINT_TWO_FAIL";

export const QUESTION_TWO_REQUEST = "QUESTION_TWO_REQUEST";
export const QUESTION_TWO_SUCCESS = "QUESTION_TWO_SUCCESS";
export const QUESTION_TWO_FAIL = "QUESTION_TWO_FAIL";

export const QUESTION_THREE_REQUEST = "QUESTION_THREE_REQUEST";
export const QUESTION_THREE_SUCCESS = "QUESTION_THREE_SUCCESS";
export const QUESTION_THREE_FAIL = "QUESTION_THREE_FAIL";

export const QUESTION_FOUR_REQUEST = "QUESTION_FOUR_REQUEST";
export const QUESTION_FOUR_SUCCESS = "QUESTION_FOUR_SUCCESS";
export const QUESTION_FOUR_FAIL = "QUESTION_FOUR_FAIL";

export const QUESTION_FIVE_REQUEST = "QUESTION_FIVE_REQUEST";
export const QUESTION_FIVE_SUCCESS = "QUESTION_FIVE_SUCCESS";
export const QUESTION_FIVE_FAIL = "QUESTION_FIVE_FAIL";

export const QUESTION_SIX_REQUEST = "QUESTION_SIX_REQUEST";
export const QUESTION_SIX_SUCCESS = "QUESTION_SIX_SUCCESS";
export const QUESTION_SIX_FAIL = "QUESTION_SIX_FAIL";

export const QUESTION_SEVEN_REQUEST = "QUESTION_SEVEN_REQUEST";
export const QUESTION_SEVEN_SUCCESS = "QUESTION_SEVEN_SUCCESS";
export const QUESTION_SEVEN_FAIL = "QUESTION_SEVEN_FAIL";

export const SEND_CHOSEN_DATA_REQUEST = "SEND_CHOSEN_DATA_REQUEST";
export const SEND_CHOSEN_DATA_SUCCESS = "SEND_CHOSEN_DATA_SUCCESS";
export const SEND_CHOSEN_DATA_FAIL = "SEND_CHOSEN_DATA_FAIL";
